### PR TITLE
Added BAT25, BAT50, BAT75, BAT100 and WIFI LEDs

### PR DESCRIPTION
**Pull request by MarkAYoder**
Now the battery level and WIFI LEDs can be blinked.  Added blinkLEDs.py to blink all the built in LEDs.

I increased the sleep between exporting a pin and setting the direction to 200ms since 100ms sometimes failed.  It's still a hack, but it works.

--Mark

### CODE REVIEW

**Comment by RobertCNelson** [comment]
bat100 should be '26'... right?

**Comment by pdp7** [comment]
@MarkAYoder a BeagleBone Black regression was discovered with how we are integrating Blue support.  The details are here: https://forums.adafruit.com/viewtopic.php?f=49&t=123435

I've been traveling for the last week and will be home on Wednesday.  Hopefully, I'll have sometime to investigate how we can have the BeagleBone (White/Black/Green) co-exist with the BeagleBone Blue.  I'll be leaving on Thursday for Maker Faire New York so I might not actually be able to sort this out until after I get back home on Sept 25th.

For now, BB White/Black/Green users will need to use release 1.0.4.  I hope to ultimately have this resolved in a forthcoming 1.0.6 release.

**Comment by RobertCNelson** [comment]
@pdp7 

```
sudo: /opt/scripts/tools/version.sh: command not found
```
They are running an old image, so they are missing:

udev permissions on bootup (thus they need to be root)
config-pin: an old version, that doesn't recognize the blue, and it'll "want" to load something...

(it'll probally work if they run as root)

Regards,

**Comment by pdp7** [comment]
@RobertCNelson Yeah, that user is out of date but I also tried this on current image.  The regression is due to this commit by @MarkAYoder https://github.com/adafruit/adafruit-beaglebone-io-python/commit/35718a959b5b73c0774fb3e7d53fd412f1d92ec1  

It causes all BeagleBones to attempt to use the LED class /sys path even though those only exist on the Blue.

**Comment by pdp7** [comment]
thanks @MarkAYoder

**Comment by zsserg** [comment]
I can confirm that it is broken for BB Black. The pins affected are P8_07, P8_08, P8_17, P8_26 and P8_32.
As a temporary workaround one may change constants in event_gpio.h, lines 51-55:
`
#define USR_LED_RED      1001 //66 P8_07 - broken for BB black
#define USR_LED_GREEN    1002 //67 P8_08- broken for BB black
#define BAT25   1003 //27 P8_17- broken for BB black
#define BAT50   1004 //11 P8_32 broken for BB black
#define BAT75   1005 //61 P8_26 broken for BB black
`

**Pull request merged**
