### PR TITLE
Added support for retrieving the gpio file descriptor within python.

### LINKED ISSUE #112: [feature] Add a get_fd() method
Hello, 
I think it could be interesting to retrieve the file descriptor of a GPIO, mostly for custom python event detects, (for example, asyncio add_reader, select, poll, etc..).

I already added this feature on my fork, but i'm pretty sure it's far from being optimal.

let me know what you think. 

-l

### PR DESCRIPTION
**Pull request by lromor**
there are also some minor changes regarding spaces and indentation, tell me if you need a cleaner pull request.
closes #112

### CODE REVIEW

**Comment by pdp7** [comment]
@lromor thanks for the PR.  Is there a test that could be added for this in `tests`?

**Comment by lromor** [comment]
I have still to think about it

**Comment by pdp7** [comment]
@lromor from #112, you wrote:
>  think it could be interesting to retrieve the file descriptor of a GPIO, mostly for custom python event detects, (for example, asyncio add_reader, select, poll, etc..).

Is there an example I can use to test this functionality?

**Comment by lromor** [comment]
Hello @pdp7 , I'm very sorry but I'm really busy lately, just give me a couple of weeks and I will prepare a better pull request.

**Comment by pdp7** [comment]
thanks @lromor

**Comment by pdp7** [comment]
@lromor any update on this?

**Comment by lromor** [comment]
well after digging a bit, I think this feature is unnecessary :( .
I'm a bit disappointed about asyncio fd support, I wanted to "yield from" (without the need to use the asyncio.*call_thread_safe*) a gpio object in such a way that the yield from is not returned until the gpio receives an interrupt... but it seems that the https://docs.python.org/3/library/asyncio-eventloop.html#asyncio-watch-read-event
api simply gives you a callback function which is something that you already provide through a thread. 

sorry for the time wasted.

-l

**Comment by pdp7** [comment]
@lromor thanks for investigating this and letting me know.

**Pull request closed without merging**
