### PR TITLE
Support for PWM in 4.1+

### PR DESCRIPTION
**Pull request by MatthewWest**
This patch does several things. Principally, it:

- Adds support for the changed PWM `sysfs` interface in Linux 4.1+
- Updates tests to reflect changes in Linux 4.1+
- Changes return conventions, from nonzero as success to the more conventional nonzero as failure. Also switch to using an `enum` error type specific to the library.
- Use the new, preferred method of using the capemanager - using the [beaglebone-universal-io](https://github.com/cdsteinkuehler/beaglebone-universal-io) library.
- Replace home-rolled `build_path` implementation with a call to `glob`, the system library.
- Include guards in all header files to handle double-includes

Numerous parts of the code were modified, as it was necessary in order to implement the different error handling convention.

One known limitation of the change is that the disable section does not unexport PWMs, it merely disables them. That means that the hardware is still powered (and probably clocked), it simply isn't putting out an output.

Tests are all passing on both Python 2 and Python 3 on Linux kernel 4.1.15-bone11. I haven't been able to test on 3.8 yet (working on it).

### CODE REVIEW

**Comment by MatthewWest** [comment]
Addresses #103

**Comment by pdp7** [comment]
@MatthewWest: awesome!  I'll try it out with set of Debian images that I test with and post my results here.

**Comment by pdp7** [comment]
@MatthewWest I installed Adafruit_BBIO from your repo:
https://github.com/MatthewWest/adafruit-beaglebone-io-python/

onto the Debian Jessie 8.5 image with Linux 4.4:
```
root@beaglebone:~/pr-matthew-west/adafruit-beaglebone-io-python# cat /etc/debian_version 
8.5
root@beaglebone:~/pr-matthew-west/adafruit-beaglebone-io-python# uname -a
Linux beaglebone 4.4.11-ti-r29 #1 SMP Fri May 27 22:58:36 UTC 2016 armv7l GNU/Linux
root@beaglebone:~/pr-matthew-west/adafruit-beaglebone-io-python# cat /etc/dogtag 
BeagleBoard.org Debian Image 2016-06-05
```

test/test_pwm_setup.py encounters several AssertionErrors:
```
E       assert <function exists at 0xb6cf7d30>('/sys/devices/platform/ocp/48302000.epwmss/48302200.ehrpwm/pwm/pwmchip2/pwm0')
E       assert <function exists at 0xb6cf7d30>('/sys/devices/platform/ocp/48302000.epwmss/48302200.ehrpwm/pwm/pwmchip2/pwm0')
E       assert <function exists at 0xb6cf7d30>('/sys/devices/platform/ocp/48302000.epwmss/48302200.ehrpwm/pwm/pwmchip2/pwm0')
E       assert <function exists at 0xb6cf7d30>('/sys/devices/platform/ocp/48302000.epwmss/48302200.ehrpwm/pwm/pwmchip2/pwm0')
E       assert <function exists at 0xb6cf7d30>('/sys/devices/platform/ocp/48302000.epwmss/48302200.ehrpwm/pwm/pwmchip2/pwm0')
```
Full test results with full error messages:
https://gist.github.com/pdp7/86919d099afb3c5394945f060fabb959

The issue seems to be that this dir exists:
```
# ls /sys/devices/platform/ocp/48302000.epwmss/
48302180.eqep  48302200.pwm  driver  driver_override  modalias	of_node  power	subsystem  uevent
```

but the desired subdir does not:
```
# ls /sys/devices/platform/ocp/48302000.epwmss/48302200.ehrpwm
ls: cannot access /sys/devices/platform/ocp/48302000.epwmss/48302200.ehrpwm: No such file or directory
```

**Comment by pdp7** [comment]
For Debian 7.11 with Linux 3.8.13:
```
debian@beaglebone:~/adafruit-beaglebone-io-python$ uname -a
Linux beaglebone 3.8.13-bone80 #1 SMP Wed Jun 15 17:03:55 UTC 2016 armv7l GNU/Linux
debian@beaglebone:~/adafruit-beaglebone-io-python$ cat /etc/debian_version 
7.11
debian@beaglebone:~/adafruit-beaglebone-io-python$ cat /etc/dogtag 
BeagleBoard.org Debian Image 2016-06-15
```

Errors from py.test:
```
>       ADC.setup()
E       RuntimeError: Unable to setup ADC system. Possible causes are: 
E         - A cape with a conflicting pin mapping is loaded 
E         - A device tree object is loaded that uses the same name for a fragment: helper
>       ADC.setup()
E       RuntimeError: Unable to setup ADC system. Possible causes are: 
E         - A cape with a conflicting pin mapping is loaded 
E         - A device tree object is loaded that uses the same name for a fragment: helper
>       ADC.setup()
E       RuntimeError: Unable to setup ADC system. Possible causes are: 
E         - A cape with a conflicting pin mapping is loaded 
E         - A device tree object is loaded that uses the same name for a fragment: helper
>       ADC.setup()
E       RuntimeError: Unable to setup ADC system. Possible causes are: 
E         - A cape with a conflicting pin mapping is loaded 
E         - A device tree object is loaded that uses the same name for a fragment: helper
>       PWM.start("P9_14", 0)
E       RuntimeError: Unknown error
>       PWM.start("P9_14", 0, 2000, 1)
E       RuntimeError: Unknown error
>       PWM.start("P9_14", 0, 2000)
E       RuntimeError: Unknown error
>       PWM.start("P9_14", 0, 2000, 0)
E       RuntimeError: Unknown error
>       PWM.start("P9_14", 0)
E       RuntimeError: Unknown error
>       PWM.start("P9_14", 100)
E       RuntimeError: Unknown error
>       PWM.start("P9_14", 0)
E       RuntimeError: Unknown error
>       PWM.start("P9_14", 0)
E       RuntimeError: Unknown error
>       PWM.start("P9_14", 0)
E       RuntimeError: Unknown error
>       PWM.start("P9_14", 0)
E       RuntimeError: Unknown error
>       PWM.start("P9_14", 0)
E       RuntimeError: Unknown error
>       PWM.start("P9_14", 0)
E       RuntimeError: Unknown error
>       SPI(1,1)
E       IOError: [Errno 2] No such file or directory
>           UART.setup("UART1")
E           RuntimeError: Unable to export UART channel.
>           UART.setup("UART1")
E           RuntimeError: Unable to export UART channel.
```

Full listing of errors:
https://gist.github.com/pdp7/c5344c1a71f33b6b7f793b9723dd3223

**Comment by pdp7** [comment]
I installed the `linux-image-4.1.29-bone22` package on the Debian 7.11 image:
```
debian@beaglebone:~$ uname -a
Linux beaglebone 4.1.29-bone22 #1 Fri Aug 5 15:16:03 UTC 2016 armv7l GNU/Linux
debian@beaglebone:~$ cat /etc/dogtag 
BeagleBoard.org Debian Image 2016-06-15
debian@beaglebone:~$ cat /etc/debian_version 
7.11
```

Errors from py.test:
https://gist.github.com/pdp7/c5344c1a71f33b6b7f793b9723dd3223#gistcomment-1846060

**Comment by pdp7** [comment]
For Debian 8.3 image with 4.1 kernel:
```
debian@beaglebone:~/adafruit-beaglebone-io-python$ cat /etc/dogtag 
BeagleBoard.org Debian Image 2016-01-24
debian@beaglebone:~/adafruit-beaglebone-io-python$ uname -a
Linux beaglebone 4.1.15-ti-rt-r43 #1 SMP PREEMPT RT Thu Jan 21 20:13:58 UTC 2016 armv7l GNU/Linux
debian@beaglebone:~/adafruit-beaglebone-io-python$ cat /etc/debian_version 
8.3
```

py.test errors messages for pwm:
https://gist.github.com/pdp7/aad85478890f37ac7a19538e9702f69c

**Comment by MatthewWest** [comment]
Should we include any necessary device trees in this library and install them? The 4.1+ code requires that the user have one of the universal device trees loaded:

```c
    // Make sure that one of the universal capes is loaded
    if (!( device_tree_loaded("cape-univ-audio") // from cdsteinkuehler/beaglebone-universal-io
        || device_tree_loaded("cape-univ-emmc")  // ""
        || device_tree_loaded("cape-univ-hdmi")  // ""
        || device_tree_loaded("cape-universal")  // ""
        || device_tree_loaded("cape-universala") // ""
        || device_tree_loaded("cape-universaln") // ""
        || device_tree_loaded("univ-all")        // from latest BeagleBone Debian 8 images
        || device_tree_loaded("univ-bbgw")       // ""
        || device_tree_loaded("univ-emmc")       // ""
        || device_tree_loaded("univ-hdmi")       // ""
        || device_tree_loaded("univ-nhdmi")))    // ""
    {
        return BBIO_CAPE;
    }
```

These images, from the [beaglebone-universal-io](https://github.com/cdsteinkuehler/beaglebone-universal-io) project, are included on new BeagleBone images (from [here](https://github.com/beagleboard/bb.org-overlays/tree/master/src/arm)), but on older images which have been upgraded to include the new kernel, they might be missing. This would also require us to switch tacks and use these overlays for the other functionality as well.

From the beaglebone-universal-io project:

> This project is a series of four overlay files, designed to work with
> the BeagleBone Black:
> 
>  * cape-universal  Exports all pins not used by HDMIN and eMMC (including audio)
>  * cape-universaln Exports all pins not used by HDMI and eMMC (no audio pins are exported)
>  * cape-univ-emmc  Exports pins used by eMMC, load if eMMC is disabled
>  * cape-univ-hdmi  Exports pins used by HDMI video, load if HDMI is disabled
>  * cape-univ-audio Exports pins used by HDMI audio

So the universal capes are not compatible with the approach used by the UART, SPI, and GPIO sections of this library.

**Comment by MatthewWest** [comment]
I've been doing a bit of looking into how other people are handling the differences between kernels 3.8 and 4.1, and it looks like we'll probably have to support both - if the universal cape is present, use it. If not (and possibly other capes are present which would conflict with which the universal cape conflicts), use a custom overlay strategy. That's at least [the conclusion](https://github.com/graycatlabs/PyBBIO/issues/80#issuecomment-128090168) that the folks over at PyBBIO came to.

**Comment by pdp7** [comment]
@MatthewWest Thanks for updating the test.

I've updated the results for Debian 8.3 image with Linux 4.1.15-ti-rt-r43:
https://gist.github.com/pdp7/aad85478890f37ac7a19538e9702f69c

I included strace log for file operations on /sys/devices.  Relevant listing of directories:
```
debian@beaglebone:~/adafruit-beaglebone-io-python$ ls /sys/devices/platform/ocp/48302000.epwmss/48302200.ehrpwm/pwm/pwmchip2/pwm0
ls: cannot access /sys/devices/platform/ocp/48302000.epwmss/48302200.ehrpwm/pwm/pwmchip2/pwm0: No such file or directory
debian@beaglebone:~/adafruit-beaglebone-io-python$ ls /sys/devices/platform/ocp/48302000.epwmss/48302200.ehrpwm/
\driver  driver_override  modalias  of_node  power  pwm  subsystem  uevent
debian@beaglebone:~/adafruit-beaglebone-io-python$ ls /sys/devices/platform/ocp/48302000.epwmss/48302200.ehrpwm/pwm/
pwmchip4
debian@beaglebone:~/adafruit-beaglebone-io-python$ ls /sys/devices/platform/ocp/48302000.epwmss/48302200.ehrpwm/pwm/pwmchip4/
device  export  npwm  power  pwm0  subsystem  uevent  unexport
debian@beaglebone:~/adafruit-beaglebone-io-python$ ls /sys/devices/platform/ocp/48302000.epwmss/48302200.ehrpwm/pwm/pwmchip4/pwm0/
duty_cycle  enable  period  polarity  power  uevent
```

I should be able to swap in the different SD cards later and run the updated test on Debian 7.11 with Linux 3.8.13 and Debian 8.5 with Linux 4.4.

**Comment by MatthewWest** [comment]
> I included strace log for file operations on /sys/devices. Relevant listing of directories:

@pdp7 am I missing something? It looks to me like the ADC is working on Linux 4.1+, so I don't need that particular `strace`.

As I see it, here's the list of the support status for each version:

- [ ] Debian 8.5, Linux 4.4 (probably fixed as of latest commits)
- [ ] Debian 8.3, Linux 4.1 (probably fixed as of latest commits)
- [ ] Debian 7.11, Linux 3.8.13 (probably still broken, not known why)
- [ ] Debian 7.11, Linux 4.1.29 (probably broken, not known why)

So what I need from you to keep working is

- `strace` results on Debian 7.11, Linux 3.8.x
- `strace` results on Debian 7.11, Linux 4.1.x
- Hopefully confirmation that Debian 8.3 and 8.5, Linux 4.1 and 4.4, are fixed (no need for `strace` if tests pass)

Thanks much for your help!

**Comment by MatthewWest** [comment]
I've run a test on Debian 7.11, Linux 3.8.13 with `strace`.

Description and results [here](https://gist.github.com/MatthewWest/c1ae5917d46751392f1604f88a9c6b1d).

**Comment by MatthewWest** [comment]
Found one problem with Debian 7.11. Updated strace output [here](https://gist.github.com/MatthewWest/c1ae5917d46751392f1604f88a9c6b1d#file-test_results2-md)

**Comment by MatthewWest** [comment]
Fixed that problem with ddbf6c3

**Comment by MatthewWest** [comment]
Alright, as of the most recent commit, ddbf6c3, we seem to be in good shape for PWM on Debian 7.11, Linux 3.8. See [here](https://gist.github.com/MatthewWest/c1ae5917d46751392f1604f88a9c6b1d#file-test_results3-md) for test logs.

**Comment by MatthewWest** [comment]
ADC error solved with 09e7597. It was an instance where I hadn't changed to match the new return value conventions - it was expecting non-zero for success.

Now just to fix SPI and UART, which are still broken on Debian 7.11.

```
sudo py.test-3
============================================== test session starts ===============================================
platform linux2 -- Python 3.2.3 -- pytest-2.2.4
collected 57 items 

test/test_adc.py ......
test/test_gpio_input.py ..
test/test_gpio_output.py ......
test/test_gpio_setup.py ..........
test/test_led.py ..
test/test_pwm_setup.py ..........................
test/test_spi.py F.
test/test_uart.py .FF

==================================================== FAILURES ====================================================
________________________________________________ TestAdc.test_spi ________________________________________________

self = <test_spi.TestAdc object at 0x668250>

    def test_spi(self):
>       SPI(1,1)
E       IOError: [Errno 2] No such file or directory

test/test_spi.py:11: IOError
_____________________________________________ TestAdc.test_setup_adc _____________________________________________

self = <test_uart.TestAdc object at 0x6688f0>

    def test_setup_adc(self):
        if kernel >= '4.1.0':
            pass
        else:
>           UART.setup("UART1")
E           RuntimeError: Unable to export UART channel.

test/test_uart.py:26: RuntimeError
________________________________________ TestAdc.test_setup_adc_multiple _________________________________________

self = <test_uart.TestAdc object at 0x6682b0>

    def test_setup_adc_multiple(self):
        if kernel >= '4.1.0':
            pass
        else:
>           UART.setup("UART1")
E           RuntimeError: Unable to export UART channel.

test/test_uart.py:32: RuntimeError
====================================== 3 failed, 54 passed in 18.56 seconds ======================================
```

**Comment by pdp7** [comment]
Great!  I'm away from home tonight but I'll test when I return home tomorrow night (Thursday).

**Comment by MatthewWest** [comment]
Found the issue with SPI - there wasn't one, I just had the BB-BONELT-HDMI and BB-BONELT-HDMIN capes loaded, so it couldn't load SPIDEV1. I did switch to using `BB-SPIDEVi` rather than `ADAFRUIT-SPIi`.

**Comment by MatthewWest** [comment]
Got UART working, so that means everything is passing on Debian 7.11, Linux image 3.8.13-bone80.

```
$ uname -a
Linux beaglebone 3.8.13-bone80 #1 SMP Wed Jun 15 17:03:55 UTC 2016 armv7l GNU/Linux
$ cat /etc/dogtag 
BeagleBoard.org Debian Image 2016-06-15
$ cat /etc/debian_version 
7.11
$ sudo py.test-3
============================================== test session starts ===============================================
platform linux2 -- Python 3.2.3 -- pytest-2.2.4
collected 57 items 

test/test_adc.py ......
test/test_gpio_input.py ..
test/test_gpio_output.py ......
test/test_gpio_setup.py ..........
test/test_led.py ..
test/test_pwm_setup.py ..........................
test/test_spi.py ..
test/test_uart.py ...

=========================================== 57 passed in 25.49 seconds ===========================================
```

**Comment by pdp7** [comment]
* Debian 8.3 image (2016-01-24) with Linux kernel 4.1.15-ti-rt-r43
* Repo: https://github.com/MatthewWest/adafruit-beaglebone-io-python
  * branch: develop
  * commit: 565f2dc Fix return convention errors
* 57 passed in 6.64 seconds

**Comment by pdp7** [comment]
I'm still encountering errors for:
*  Debian 7.11 (2016-06-15) with Linux 3.8.13-bone80

```
test/test_adc.py ..FFFF
test/test_gpio_input.py ..
test/test_gpio_output.py ......
test/test_gpio_setup.py ..........
test/test_led.py ..
test/test_pwm_setup.py FFFF..FF.......F..FFFFF...
test/test_spi.py F.
test/test_uart.py .FF
```

**Comment by pdp7** [comment]
### Debian 7.11 (2016-06-15) with Linux 3.8.13-bone80
* I uncommented this line in `/boot/uEnv.txt` so that HDMI and eMMC are disabled:
```
cape_disable=capemgr.disable_partno=BB-BONELT-HDMI,BB-BONELT-HDMIN,BB-BONE-EMMC-2G
```
* All tests passed OK:
```
test/test_adc.py ......
test/test_gpio_input.py ..
test/test_gpio_output.py ......
test/test_gpio_setup.py ..........
test/test_led.py ..
test/test_pwm_setup.py ..........................
test/test_spi.py ..
test/test_uart.py ...
```

**Comment by pdp7** [comment]
### Debian 8.5 (2016-06-05) with Linux 4.4.11-ti-r29
All 57 pass OK:
```
test/test_adc.py ......
test/test_gpio_input.py ..
test/test_gpio_output.py ......
test/test_gpio_setup.py ..........
test/test_led.py ..
test/test_pwm_setup.py ..........................
test/test_spi.py ..
test/test_uart.py ...
```

**Comment by pdp7** [comment]
### Debian 7.11 (2016-06-15) with Linux 4.1.29-bone22
I did a clean build after booting into the 4.1 kernel.  I also uncommented this in `/boot/uEnv.txt` to avoid HDMI conflict:
```
dtb=am335x-boneblack-emmc-overlay.dtb
```
I also installed the current [beagleboard/bb.org-overlays](https://github.com/beagleboard/bb.org-overlays).

[pwm and spi show errors](https://gist.github.com/pdp7/dbdf9a6d0160c8f15616e07bfa49f639):
```
test/test_adc.py ......
test/test_gpio_input.py ..
test/test_gpio_output.py ......
test/test_gpio_setup.py ..........
test/test_led.py ..
test/test_pwm_setup.py FFFF..FF.......F..FFFFF...
test/test_spi.py F.
test/test_uart.py ...
```

**Comment by pdp7** [comment]
### Debian 7.11 (2016-06-15) with Linux 4.1.29-bone22
I installed [beaglebone-universal-io](https://github.com/cdsteinkuehler/beaglebone-universal-io).  Now just pwm test fails:
```
test/test_adc.py ......
test/test_gpio_input.py ..
test/test_gpio_output.py ......
test/test_gpio_setup.py ..........
test/test_led.py ..
test/test_pwm_setup.py FFFF..FF.......F..F.......
test/test_spi.py ..
test/test_uart.py ...
```

```
debian@beaglebone:~/adafruit-beaglebone-io-python$ cat /sys/devices/platform/bone_capemgr/slots
 0: PF----  -1 
 1: PF----  -1 
 2: PF----  -1 
 3: PF----  -1 
 4: P-O-L-   0 Override Board Name,00A0,Override Manuf,univ-emmc
 5: P-O-L-   1 Override Board Name,00A0,Override Manuf,BB-ADC
```

**Comment by pdp7** [comment]
@MatthewWest: all of these have passed OK.  Thanks!
- [x] Debian 8.5 (2016-06-05) with Linux 4.4.11-ti-r29
- [x] Debian 8.3 image (2016-01-24) with Linux kernel 4.1.15-ti-rt-r43
- [x] Debian 7.11 (2016-06-15) with Linux 3.8.13-bone80
- [x] Debian 7.11 (2016-06-15) with Linux 4.1.29-bone22

@jwcooper @ladyada @tdicola: I recommend this PR be merged.

**Comment by pdp7** [comment]
@ladyada or @jwcooper: could you please merge this pull request?

**Comment by pdp7** [comment]
Thanks @ladyada for merging.  And thanks very much to @MatthewWest!!

**Comment by Dark-Guan** [comment]
I use Linux kamikaze 4.1.6-bone15 #1 Tue Aug 18 12:45:47 UTC 2015 armv7l GNU/Linux

  File "testHardPwm.py", line 6, in <module>
    PWM.start("P9_14", 50 , 2000, 1)
RuntimeError: Problem with a sysfs file

When I run testing demo, the error I get above.
It's nice that  if some body can tell me the problem,thanks!

**Comment by MatthewWest** [comment]
@Dark-Guan My guess is that the beaglebone-universal-io capes are not present. Can you list results of the following commands:

- `cat /sys/devices/platform/bone_capemgr/slots`
- `ls /sys/devices/platform/ocp/`
- `ls /lib/firmware`

Try those first. We may have to resort to `strace` if they don't work, but that's a bit more tedious. Try those, and hopefully we can figure out what's happening

**Comment by Dark-Guan** [comment]
@MatthewWest Thanks for your reponse.

root@kamikaze:~# cat /sys/devices/platform/bone_capemgr/slots
 0: PF----  -1 
 1: PF----  -1 
 2: PF----  -1 
 3: PF----  -1 
 4: P-O-L-   0 Override Board Name,00A0,Override Manuf,cape-universal
root@kamikaze:~# ls /sys/devices/platform/ocp/
40300000.ocmcram  4804c000.gpio			 48310000.rng	    ocp:P8_15_pinmux  ocp:P9_24_pinmux
44d00000.wkup_m3  48060000.mmc			 49000000.edma	    ocp:P8_16_pinmux  ocp:P9_26_pinmux
44e07000.gpio	  480c8000.mailbox		 4a100000.ethernet  ocp:P8_17_pinmux  ocp:P9_27_pinmux
44e09000.serial   480ca000.spinlock		 4a300000.pruss     ocp:P8_18_pinmux  ocp:P9_30_pinmux
44e0b000.i2c	  4819c000.i2c			 53100000.sham	    ocp:P8_19_pinmux  ocp:P9_41_pinmux
44e35000.wdt	  481a0000.spi			 53500000.aes	    ocp:P8_26_pinmux  ocp:P9_42_pinmux
44e3e000.rtc	  481a8000.serial		 56000000.sgx	    ocp:P9_11_pinmux  ocp:P9_91_pinmux
47400000.usb	  481ac000.gpio			 driver_override    ocp:P9_12_pinmux  ocp:P9_92_pinmux
48022000.serial   481ae000.gpio			 modalias	    ocp:P9_13_pinmux  ocp:cape-universal
48024000.serial   481cc000.can			 ocp:P8_07_pinmux   ocp:P9_14_pinmux  ocp:l4_wkup@44c00000
4802a000.i2c	  481d0000.can			 ocp:P8_08_pinmux   ocp:P9_15_pinmux  of_node
48030000.spi	  481d8000.mmc			 ocp:P8_09_pinmux   ocp:P9_16_pinmux  power
48042000.timer	  48200000.interrupt-controller  ocp:P8_10_pinmux   ocp:P9_17_pinmux  subsystem
48044000.timer	  48300000.epwmss		 ocp:P8_11_pinmux   ocp:P9_18_pinmux  uevent
48046000.timer	  48302000.epwmss		 ocp:P8_12_pinmux   ocp:P9_21_pinmux
48048000.timer	  48304000.epwmss		 ocp:P8_13_pinmux   ocp:P9_22_pinmux
4804a000.timer	  4830e000.lcdc			 ocp:P8_14_pinmux   ocp:P9_23_pinmux
root@kamikaze:~# ls /lib/firmware
ADAFRUIT-SPI0-00A0.dtbo     BB-BONE-SERL-03-00A1.dtbo	GHI-LCD-00A0.dtbo	      carl9170-1.fw
ADAFRUIT-SPI1-00A0.dtbo     BB-BONE-WL1837-00A0.dtbo	LICENCE.atheros_firmware      dev-USB-PWR-CTL-00A1.dtbo
ADAFRUIT-UART1-00A0.dtbo    BB-BONE-WTHR-01-00B0.dtbo	LICENCE.broadcom_bcm43xx      dra7-ipu2-fw.xem4
ADAFRUIT-UART2-00A0.dtbo    BB-CAN1-00A0.dtbo		LICENCE.rtlwifi_firmware.txt  dra7xx-m4-ipu2.xem4
ADAFRUIT-UART4-00A0.dtbo    BB-CAPE-DISP-CT4-00A0.dtbo	LICENCE.ti-connectivity       htc_7010.fw
ADAFRUIT-UART5-00A0.dtbo    BB-I2C1-00A0.dtbo		NL-AB-BBBC-00D0.dtbo	      htc_9271.fw
BB-ADC-00A0.dtbo	    BB-I2C1-PCA9685-00A0.dtbo	RTL8192E		      mt7601u.bin
BB-BBBMINI-00A0.dtbo	    BB-I2C2-0A00.dtbo		am33xx_pwm-00A0.dtbo	      rt2561.bin
BB-BONE-AUDI-02-00A0.dtbo   BB-PWM0-00A0.dtbo		ar3k			      rt2561s.bin
BB-BONE-BACONE-00A0.dtbo    BB-PWM1-00A0.dtbo		ar5523.bin		      rt2661.bin
BB-BONE-BBH-00A1.dtbo	    BB-PWM2-00A0.dtbo		ar7010.fw		      rt2860.bin
BB-BONE-BBH-00A2.dtbo	    BB-RELAY-4PORT-00A0.dtbo	ar7010_1_1.fw		      rt2870.bin
BB-BONE-CRAMPS-00B4.dtbo    BB-RTC-01-00A0.dtbo		ar9271.fw		      rt3070.bin
BB-BONE-CRAMPS-00B5.dtbo    BB-SPI0-MCP3008-00A0.dtbo	ath10k			      rt3071.bin
BB-BONE-CRYPTO-00A0.dtbo    BB-SPIDEV0-00A0.dtbo	ath3k-1.fw		      rt3090.bin
BB-BONE-DVID-01-00A3.dtbo   BB-SPIDEV1-00A0.dtbo	ath6k			      rt3290.bin
BB-BONE-LCD3-01-00A2.dtbo   BB-SPIDEV1A1-00A0.dtbo	ath9k_htc		      rt73.bin
BB-BONE-LCD4-01-00A1.dtbo   BB-UART1-00A0.dtbo		bone_eqep0-00A0.dtbo	      rtl_bt
BB-BONE-LCD5-01-00A1.dtbo   BB-UART2-00A0.dtbo		bone_eqep1-00A0.dtbo	      rtl_nic
BB-BONE-LCD7-01-00A1.dtbo   BB-UART2-RTSCTS-00A0.dtbo	bone_eqep2-00A0.dtbo	      rtlwifi
BB-BONE-LCD7-01-00A2.dtbo   BB-UART3-00A0.dtbo		bone_eqep2b-00A0.dtbo	      ti-connectivity
BB-BONE-LCD7-01-00A3.dtbo   BB-UART4-00A0.dtbo		brcm			      uio_pruss_enable-00A0.dtbo
BB-BONE-REACH-00A0.dtbo     BB-UART4-RS485-00A0.dtbo	cape-CBB-Serial-r01.dtbo      univ-all-00A0.dtbo
BB-BONE-REPLICAP-00A4.dtbo  BB-UART5-00A0.dtbo		cape-bone-ibb-00A0.dtbo       univ-bbgw-00A0.dtbo
BB-BONE-REPLICAP-00B1.dtbo  BB-VIEW-LCD4-01-00A0.dtbo	cape-univ-audio-00A0.dtbo     univ-emmc-00A0.dtbo
BB-BONE-REPLICAP-00B2.dtbo  BB-VIEW-LCD7-01-00A0.dtbo	cape-univ-emmc-00A0.dtbo      univ-hdmi-00A0.dtbo
BB-BONE-REPLICAP-00B3.dtbo  BB-W1-P9.12-00A0.dtbo	cape-univ-hdmi-00A0.dtbo      univ-nhdmi-00A0.dtbo
BB-BONE-REPLICAP-00B4.dtbo  CAP-BONE-IIO-00A0.dtbo	cape-universal-00A0.dtbo      zd1211
BB-BONE-REPLICAP-0A4A.dtbo  DVK530-LCD4-01-00A0.dtbo	cape-universaln-00A0.dtbo

There is the result. 
I use cape-universaln-00A0.dtbo.
It seems  48300000.epwmss is wired ,there is some different with the file directory.

**Comment by MatthewWest** [comment]
@Dark-Guan Alright, I don't see an easy answer based on what you've provided so far. Can you please run the following commands, and paste the output (`trace.txt`) into a [gist](gist.github.com) for us to look at?

```bash
# Install strace somehow (not sure what the package management situation is on kamikaze)
# on Debian it'd be
sudo apt-get install strace
sudo strace -o trace.txt python3
```

```python
from Adafruit_BBIO import PWM
PWM.start("P9_14", 50 , 2000, 1)
# press Ctrl-D
```

Then upload the contents of `trace.txt` into a gist here.

If you're not familiar with it, `strace` is a fantastic tool for seeing what system commands a program makes (file opening, writing, etc.). Hopefully this will let us see what errors it is hitting.

**Comment by Dark-Guan** [comment]
Ok,Thanks @MatthewWest I will test it soon!  Trace is very a nice tool !

**Comment by Dark-Guan** [comment]
@MatthewWest  https://github.com/Dark-Guan/No-Used-Things/blob/master/trace.txt
I've uploaded "trace.txt" there . Thanks very much

**Comment by MatthewWest** [comment]
I figured it out. Here's the critical part:

```
open("/sys/devices/platform/ocp/48302000.epwmss/48302200.ehrpwm/pwm/pwmchip2/pwm0/period", O_RDWR) = 3
open("/sys/devices/platform/ocp/48302000.epwmss/48302200.ehrpwm/pwm/pwmchip2/pwm0/duty_cycle", O_RDWR) = 4
open("/sys/devices/platform/ocp/48302000.epwmss/48302200.ehrpwm/pwm/pwmchip2/pwm0/polarity", O_RDWR) = 5
open("/sys/devices/platform/ocp/48302000.epwmss/48302200.ehrpwm/pwm/pwmchip2/pwm0/enable", O_RDWR) = 6
lseek(6, 0, SEEK_SET)                   = 0
read(6, "0", 1)                         = 1
lseek(5, 0, SEEK_SET)                   = 0
write(5, "inversed", 8)                 = 8
lseek(6, 0, SEEK_SET)                   = 0
write(6, "1", 1)                        = 1
lseek(4, 0, SEEK_SET)                   = 0
write(4, "250000", 6)                   = -1 EINVAL (Invalid argument)
```

The invalid argument when setting the duty cycle happens when the duty cycle is set to longer than the period of the pwm. This was happening because we weren't reading the current duty_ns and period_ns from the files. I've written a short patch which reads the current duty_ns and pwm_ns from the files before setting the default values, in order to set the duty and period in the correct order.

That said, I've written the changes but don't have access to a BeagleBone for the next 2 weeks. So I haven't tested my changes at all, even to see if it will compile. You're welcome to try the code in [the develop branch of my repository](https://github.com/MatthewWest/adafruit-beaglebone-io-python/tree/develop). I won't submit a pull request until I've had a chance to test it.

**Comment by Dark-Guan** [comment]
@MatthewWest  OK, Nice work ! I will spend some time to test yours develop version. Thanks very much !

**Comment by pdp7** [comment]
All tests I've run are OK for @MatthewWest's `develop` branch:

* [x] Debian 8.5 (2016-08-14):
  * [x] Linux beaglebone 4.1.15-bone18 #1 Wed Jan 13 00:05:20 UTC 2016 armv7l GNU/Linux
  * [x] Linux beaglebone 4.1.14-bone17 #1 Thu Dec 10 23:08:42 UTC 2015 armv7l GNU/Linux
  * [x] Linux beaglebone 4.1.6-bone15 #1 Tue Aug 18 12:45:47 UTC 2015 armv7l GNU/Linux

* [x] Debian 8.5 (2016-06-05):
  * [x] Linux beaglebone 4.4.11-ti-r29 #1 SMP Fri May 27 22:58:36 UTC 2016 armv7l GNU/Linux

* [x] Debian 8.2 (2015-12-07):
  * [x] Linux beaglebone 4.1.13-ti-r35 #1 SMP PREEMPT Thu Dec 3 20:56:01 UTC 2015 armv7l GNU/Linux
  * [x] Linux beaglebone 4.4.19-bone13 #1 Mon Aug 29 23:57:47 CDT 2016 armv7l GNU/Linux

* Debian 7.5 (2014-05-14):
  * [x] Linux beaglebone 3.8.13-bone50 #1 SMP Tue May 13 13:24:52 UTC 2014 armv7l GNU/Linux

**Comment by pdp7** [comment]
@MatthewWest If you can create a pull request with the fix from your develop branch, then I will test again and merge if no issues.

**Comment by tomek242** [comment]
Hello folks.
Maybe You help me with my problem.
I try to build simply mobile robot based on this project:
http://myroboticadventure.blogspot.com/2014/05/my-first-working-robot-its-alive.html
I use Debian 7.11 with standard kernel and standard Adafruit I/O library taken from here:
https://learn.adafruit.com/setting-up-io-python-library-on-beaglebone-black/installation-on-ubuntu
When I try to wrote simple program in Python like this:

import Adafruit_BBIO.PWM as PWM
import time
pin1 = "P9_14"
pin2 = "P9_16"
pin3 = "P8_13"
pin4 = "P8_16"
PWM.start(pin1,0)
PWM.start(pin2,0)
PWM.start(pin3,0)
PWM.start(pin4,0)
for i in range(0, 100):
PWM.set_duty_cycle(pin,80)
PWM.set_duty_cycle(pin,80)
PWM.set_duty_cycle(pin,80)
PWM.set_duty_cycle(pin,80)
time.sleep(.1)

PWM.stop(pin1)
PWM.stop(pin2)
PWM.stop(pin3)
PWM.stop(pin4)
PWM.cleanup()

my BBB show me a errors: Duty is larger than periodand, only rotates with three wheels, output P9_14 as if it did not work at all. After restart my BBB does not boot the wheels at all, and display message: Invalid sysfs file or something like that.
I was try other debian images but no result. Could someone help me in here?
Thanks.

**Pull request merged**
