### PR TITLE
Treat warnings as errors

### PR DESCRIPTION
**Pull request by cocasema**
Added '-Wall', '-Werror' to compiler flags and fixed compilation errors for python2 and python3.

### CODE REVIEW

**Comment by pdp7** [comment]
There were several improvements in #108.  Could you please check if this problem still exists?  And if so, update the pull request so that the conflicts are resolved.

**Comment by MatthewWest** [comment]
At least some of these will still apply. I didn't get to putting all of these changes in my build. I especially appreciate the makefile changes with separate builds for Python 2 and 3.

**Comment by pdp7** [comment]
@cocasema thanks for the pull request.  Unfortuantely, it now conflicts after recent merges.  Could you please resolve the current conflicts so that I can merge it?

**Comment by cocasema** [comment]
@pdp7 done

**Comment by pdp7** [comment]
## Tested OK with:
* 4.4.21-bone13  (Debian 8.6)
* 3.8.13-bone81 (Debian 7.11)

**Comment by pdp7** [comment]
Thanks @cocasema!

**Pull request merged**
