### PR TITLE
Timeout support for wait_for_edge

### PR DESCRIPTION
**Pull request by jpbarraca**
This change makes it able to wait for an edge change but bail out if no change is detected after a timeout. 
The code should be mostly backward compatible but enables programs to recover when the hardware goes weird.

The function wait_for_edge will now admit a timeout value and will return 0 or -1 . If the return is 0, an edge change is detected. If the return is -1 a timeout occurred.

### CODE REVIEW

**Comment by melvin837** [comment]
It finally worked for me!!! While I was runnig the BBB on Ubuntu, I never managed to make it work. After I switched to Debian, It worked perfectly right after installing.

Thank you!

**Comment by jpbarraca** [comment]
Great.  I will add this info to the readme.

Any idea what was wrong? I could not reproduce your results because the distribution I used was also Debian.

cheers.

**Comment by melvin837** [comment]
No idea. I purged the old GPIO library, and deleted all the remaining files from the dist-packages directories. Then I re-installed it from your Git. Even though there were no compilation errors, I still got the TypeError message when using the wait_for_edge function.

I had some other issues with that OS (Ubuntu 13.10 // 2013-09-04 image), therefore I switched to Debian.

**Comment by pdp7** [comment]
@jpbarraca There were several improvements from merged PRs since this PR was created, most recently in #108. Please check if this is still an issue and if the PR still resolves the issue.

**Comment by pdp7** [comment]
@jpbarraca thanks for the pull request. Unfortuantely, it now conflicts after recent merges. Could you please resolve the conflict so that I can test this PR?

**Comment by pdp7** [comment]
@jpbarraca  It looks like there are some conflicts now in `source/event_gpio.h`.  Could you please take a look?  Thanks!

**Comment by jpbarraca** [comment]
@pdp7 No conflicts now.

**Comment by pdp7** [comment]
Thanks, I'll test it out.

**Comment by pdp7** [comment]
@jpbarraca I got this error when trying to install from your master:
```
source/py_gpio.c: In function 'py_wait_for_edge':
source/py_gpio.c:465:13: error: too many arguments to function 'blocking_wait_for_edge'
    result = blocking_wait_for_edge(gpio, edge, timeout);
```

Here's the full output:
```
root@beaglebone:~/pr# git clone https://github.com/jpbarraca/adafruit-beaglebone-io-python
Cloning into 'adafruit-beaglebone-io-python'...
remote: Counting objects: 1049, done.
remote: Total 1049 (delta 0), reused 0 (delta 0), pack-reused 1049
Receiving objects: 100% (1049/1049), 225.65 KiB | 0 bytes/s, done.
Resolving deltas: 100% (683/683), done.
Checking connectivity... done.
root@beaglebone:~/pr# cd adafruit-beaglebone-io-python/
root@beaglebone:~/pr/adafruit-beaglebone-io-python# ls
Adafruit_BBIO  Adafruit_I2C.py	CHANGELOG.rst  MANIFEST.in  Makefile  README.rst  distribute_setup.py  fix_py_compile.py  overlays  setup.py  source  test  tox.ini
root@beaglebone:~/pr/adafruit-beaglebone-io-python# python ./setup.py install
running install
running bdist_egg
running egg_info
creating Adafruit_BBIO.egg-info
writing Adafruit_BBIO.egg-info/PKG-INFO
writing top-level names to Adafruit_BBIO.egg-info/top_level.txt
writing dependency_links to Adafruit_BBIO.egg-info/dependency_links.txt
writing manifest file 'Adafruit_BBIO.egg-info/SOURCES.txt'
reading manifest file 'Adafruit_BBIO.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'Adafruit_BBIO.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build
creating build/lib.linux-armv7l-2.7
copying Adafruit_I2C.py -> build/lib.linux-armv7l-2.7
creating build/lib.linux-armv7l-2.7/Adafruit_BBIO
copying Adafruit_BBIO/__init__.py -> build/lib.linux-armv7l-2.7/Adafruit_BBIO
creating build/lib.linux-armv7l-2.7/overlays
copying overlays/builder.py -> build/lib.linux-armv7l-2.7/overlays
copying overlays/__init__.py -> build/lib.linux-armv7l-2.7/overlays
running build_ext
building 'Adafruit_BBIO.GPIO' extension
creating build/temp.linux-armv7l-2.7
creating build/temp.linux-armv7l-2.7/source
arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DBBBVERSION41 -I/usr/include/python2.7 -c source/py_gpio.c -o build/temp.linux-armv7l-2.7/source/py_gpio.o -Wall -Werror -Wno-format-security
In file included from source/py_gpio.c:34:0:
source/event_gpio.h:72:5: error: conflicting types for 'blocking_wait_for_edge'
 int blocking_wait_for_edge(unsigned int gpio, unsigned int edge);
     ^
source/event_gpio.h:71:5: note: previous declaration of 'blocking_wait_for_edge' was here
 int blocking_wait_for_edge(unsigned int gpio, unsigned int edge, int timeout);
     ^
source/py_gpio.c: In function 'py_wait_for_edge':
source/py_gpio.c:465:13: error: too many arguments to function 'blocking_wait_for_edge'
    result = blocking_wait_for_edge(gpio, edge, timeout);
             ^
In file included from source/py_gpio.c:34:0:
source/event_gpio.h:72:5: note: declared here
 int blocking_wait_for_edge(unsigned int gpio, unsigned int edge);
     ^
error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
```

**Comment by pdp7** [comment]
@jpbarraca hi, any update on this?

**Comment by jpbarraca** [comment]
Fixed but needs testing. Will try to do it tonight.

**Comment by jpbarraca** [comment]
Closing this PR as the error is way too simple for such long history. Will open again today.

**Pull request closed without merging**
