### PR TITLE
Encoder: do kernel check, PEP8 cleanup

### PR DESCRIPTION
**Pull request by dplanella**
- Added a check for kernels >= 4.4
- Cleaned up formatting for the module to be PEP8-compliant

While the diff is quite big, the change is minimal (added kernel check). I've changed all indentations to 4 spaces, removed trailing whitespace, etc. to make the module PEP8-compliant. I thought it had to be done before further additions to the module, so now is probably a good time as any :)

To double-check no further changes were introduced, the diff can be done with an external tool filtering out the whitespace changes.

### CODE REVIEW

**Comment by pdp7** [comment]
thanks @dplanella

**Comment by pdp7** [comment]
#201 has been merged.  Thanks.

**Comment by pdp7** [comment]
@dplanella fyi - the logic for the kernel check does not seem to be correct.

The ImportError message states `Encoder module requires Linux kernel version >= 4.4.x` but code is checking exactly for `4.4`.  It throws an error for any version great than `4.4` such as `4.14`.
```
debian@beaglebone:~/ssh/adafruit-beaglebone-io-python$ python -c 'import Adafruit_BBIO.Encoder'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "Adafruit_BBIO/Encoder.py", line 13, in <module>
    'Your Linux kernel version is {}.'.format(platform.release()))
ImportError: The Encoder module requires Linux kernel version >= 4.4.x.
Please upgrade your kernel to use this module.
Your Linux kernel version is 4.14.0-ti-r9.
```

**Comment by dplanella** [comment]
@pdp7 apologies, I can see where it went wrong. Fixed now on PR #202.

**Pull request merged**
