### PR TITLE
Add support for Python 3

### PR DESCRIPTION
**Pull request by westphahl**

### CODE REVIEW

**Comment by tdicola** [comment]
Awesome, thanks for taking the time to sort out what needed to be done for Python 3!  Just to check, it looks like this is also backwards compatible with recent versions of python 2 (using some #ifdefs etc. to smooth over differences in C extensions with python 2 and 3), right?

Also I'm curious is there anything broken with keeping the angstrom-specific check for py_compile.py in the setup.py?  I noticed it's removed but am curious we can keep it in just in case someone is still using the older angstrom builds.  Unfortunately since it uses urllib2 I'm guessing it's trickier to use in python 3?

**Comment by westphahl** [comment]
From what I have tested the C extension is compatible with Python >= 2.7 and Python >= 3. 
I also updated the pull request to have the py_compile fix in a separate script.

**Comment by westphahl** [comment]
Please let me know if you think there is more that needs to be changed.

**Comment by tdicola** [comment]
Oh that looks great, yeah I like the idea of just putting the fix script to the side if anyone needs it.  I'll grab a BBB and give it a quick test later today.  Thanks!

**Comment by tdicola** [comment]
Gave it a quick test with python 2 and 3 to toggle some GPIO pins and it works great!  Thanks again for contributing the fixes, just merged it in.

**Pull request merged**
