### PR TITLE
Wait until GPIO file appears on the /sys filesystem (issue #36)

### PR DESCRIPTION
**Pull request by olegantonyan**
Fixed issue #36 with non-root access to GPIO

### CODE REVIEW

**Comment by pdp7** [comment]
@olegantonyan There have been several PRs merged, most recently #108.  Could you please check to see if this is an issue and that your PR resolves the issue?

**Comment by olegantonyan** [comment]
It's been so long ago I don't remember the actual problem :) I need a bit more time to reproduce it

**Comment by pdp7** [comment]
@olegantonyan Thanks for the update.  I'll try out this fix from your branch so that I can better understand the issue.

**Comment by pdp7** [comment]
@olegantonyan  thanks for the pull request. Unfortuantely, it now conflicts after recent merges. Could you please resolve the conflict so that I can test this PR?

**Comment by olegantonyan** [comment]
This should probably work :)

**Comment by pdp7** [comment]
Tested OK on:

### 3.8.13-bone80
* BeagleBoard.org Debian Image 2016-06-15
* Debian 7.11
```
root@beaglebone:~/olegantonyan-bbio# pytest
platform linux2 -- Python 2.7.3, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /root/olegantonyan-bbio, inifile: 
collected 57 items 

test/test_adc.py ......
test/test_gpio_input.py ..
test/test_gpio_output.py ......
test/test_gpio_setup.py ..........
test/test_led.py ..
test/test_pwm_setup.py ..........................
test/test_spi.py ..
test/test_uart.py ...

57 passed in 46.69 seconds
```

### 4.1.30-ti-r69
* BeagleBoard.org Debian Image 2016-08-14
* Debian 8.6
```
root@beaglebone:~/olegantonyan-bbio# pytest
platform linux2 -- Python 2.7.9, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /root/olegantonyan-bbio, inifile: 
collected 57 items 

test/test_adc.py ......
test/test_gpio_input.py ..
test/test_gpio_output.py ......
test/test_gpio_setup.py ..........
test/test_led.py ..
test/test_pwm_setup.py ..........................
test/test_spi.py ..
test/test_uart.py ...
57 passed in 46.20 seconds
```

**Comment by pdp7** [comment]
@olegantonyan  thanks for your efforts!

**Pull request merged**
