### PR TITLE
source/common.c: add initial PocketBeagle values

### PR DESCRIPTION
**Pull request by RobertCNelson**
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

Just a WIP, this table was fun to generate, totally un-tested.

### CODE REVIEW

**Comment by RobertCNelson** [comment]
So far testing with: 4.4.91-ti-r133
```
import Adafruit_BBIO.PWM as PWM
myPWM="P2_1"
PWM.start(myPWM, 0, 1000)
PWM.set_duty_cycle(myPWM, 50)
```
The 4th patch needs to be cleaned-up, the code is expecting a certain overlay to be installed.  With u-boot overlays and the PocketBeagle we need to ignore that..

**Comment by RobertCNelson** [comment]
4.14.0-rc4-ti-r3 now works on the PocketBeagle, like v4.9.x i had to kill the pwm_set_polarity..

**Comment by RobertCNelson** [comment]
and 4.9.54-ti-r68 now works on the PocketBeagle..

**Comment by pdp7** [comment]
thanks @RobertCNelson

**Pull request merged**
