### PR TITLE
PWM for normal GPIO

### PR DESCRIPTION
**Pull request by Dark-Guan**
This function is inspired by https://github.com/WiringPi/WiringPi
I need this funtion,So I write one to expand BBIO library.

### CODE REVIEW

**Comment by pdp7** [comment]
There were several PWM improvements in #108.  Could you please update the pull request so that the conflicts are resolved?

**Comment by Dark-Guan** [comment]
Ok，I will check it and submitl it again

**Comment by pdp7** [comment]
@Dark-Guan thank you for the pull request.  Could you please add tests for this feature to `tests/test_pwm_setup.py`?

**Comment by pdp7** [comment]
@Dark-Guan It looks like there are some conflicts now in `source/py_gpio.c` and `setup.py`.  Could you please take a look?  Thanks!

**Comment by pdp7** [comment]
@Dark-Guan hi, any update on this?

**Comment by pdp7** [comment]
Please re-open if the conflicts have been resolved.

**Pull request closed without merging**
