### PR TITLE
Add C++ library for reusing existing c code

### PR DESCRIPTION
**Pull request by cocasema**
BBIO library works well on 4.X kernels. This pull request allows to share this joy between python and c++.

What's added:
- syslog into c code for debugging
- automake files for building libadafruit-bbio
- a couple of c++ examples

### CODE REVIEW

**Comment by pdp7** [comment]
@cocasema thanks for the pull request.  This is an interesting addition.  Is the desire to write C++ programs that can take advantage of the knowledge that Adafruit_BBIO has of the BeagleBone hardware peripherals?

I'm about to travel home from a conference today but I'll review further and try it out later this week.  Thanks.

**Comment by pdp7** [comment]
@cocasema I just clone your repo, installed and ran pytest which generated `undefined symbol: gpio_direction` error.

Have you tried running pytest?

Full log of running pytest:
```
debian@beaglebone:~/pr/adafruit-beaglebone-io-python$ uname -a
Linux beaglebone 4.4.48-ti-r88 #1 SMP Sun Feb 12 01:06:00 UTC 2017 armv7l GNU/Linux

debian@beaglebone:~/pr/adafruit-beaglebone-io-python$ cat /etc/dogtag 
BeagleBoard.org Debian Image 2017-02-12

debian@beaglebone:~/pr/adafruit-beaglebone-io-python$ sudo pytest 2>&1 
============================================================================ test session starts ============================================================================
platform linux2 -- Python 2.7.9, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /home/debian/pr/adafruit-beaglebone-io-python, inifile: 
collected 38 items / 4 errors 

================================================================================== ERRORS ===================================================================================
_________________________________________________________________ ERROR collecting test/test_gpio_input.py __________________________________________________________________
ImportError while importing test module '/home/debian/pr/adafruit-beaglebone-io-python/test/test_gpio_input.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_gpio_input.py:4: in <module>
    import Adafruit_BBIO.GPIO as GPIO
build/bdist.linux-armv7l/egg/Adafruit_BBIO/GPIO.py:7: in <module>
    ???
build/bdist.linux-armv7l/egg/Adafruit_BBIO/GPIO.py:6: in __bootstrap__
    ???
E   ImportError: /root/.python-eggs/Adafruit_BBIO-1.0.3-py2.7-linux-armv7l.egg-tmp/Adafruit_BBIO/GPIO.so: undefined symbol: gpio_direction
_________________________________________________________________ ERROR collecting test/test_gpio_output.py _________________________________________________________________
ImportError while importing test module '/home/debian/pr/adafruit-beaglebone-io-python/test/test_gpio_output.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_gpio_output.py:4: in <module>
    import Adafruit_BBIO.GPIO as GPIO
build/bdist.linux-armv7l/egg/Adafruit_BBIO/GPIO.py:7: in <module>
    ???
build/bdist.linux-armv7l/egg/Adafruit_BBIO/GPIO.py:6: in __bootstrap__
    ???
E   ImportError: /root/.python-eggs/Adafruit_BBIO-1.0.3-py2.7-linux-armv7l.egg-tmp/Adafruit_BBIO/GPIO.so: undefined symbol: gpio_direction
_________________________________________________________________ ERROR collecting test/test_gpio_setup.py __________________________________________________________________
ImportError while importing test module '/home/debian/pr/adafruit-beaglebone-io-python/test/test_gpio_setup.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_gpio_setup.py:5: in <module>
    import Adafruit_BBIO.GPIO as GPIO
build/bdist.linux-armv7l/egg/Adafruit_BBIO/GPIO.py:7: in <module>
    ???
build/bdist.linux-armv7l/egg/Adafruit_BBIO/GPIO.py:6: in __bootstrap__
    ???
E   ImportError: /root/.python-eggs/Adafruit_BBIO-1.0.3-py2.7-linux-armv7l.egg-tmp/Adafruit_BBIO/GPIO.so: undefined symbol: gpio_direction
_____________________________________________________________________ ERROR collecting test/test_led.py _____________________________________________________________________
ImportError while importing test module '/home/debian/pr/adafruit-beaglebone-io-python/test/test_led.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test/test_led.py:5: in <module>
    import Adafruit_BBIO.GPIO as GPIO
build/bdist.linux-armv7l/egg/Adafruit_BBIO/GPIO.py:7: in <module>
    ???
build/bdist.linux-armv7l/egg/Adafruit_BBIO/GPIO.py:6: in __bootstrap__
    ???
E   ImportError: /root/.python-eggs/Adafruit_BBIO-1.0.3-py2.7-linux-armv7l.egg-tmp/Adafruit_BBIO/GPIO.so: undefined symbol: gpio_direction
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================================== 4 error in 2.44 seconds ==========================================================================
```

**Comment by cocasema** [comment]
> undefined symbol: gpio_direction
I apologize for that - I lost one fix-up during rebase. Just pushed updated version on cpplib branch;

**Comment by cocasema** [comment]
> Is the desire to write C++ programs that can take advantage of the knowledge that Adafruit_BBIO has of the BeagleBone hardware peripherals?

My desire was simple - to have a stable library I can use for working with BBB. I need both - python and c++, mainly for writing [ROS](http://www.ros.org/) nodes. Adafruit_BBIO was the best choice for python - supported and up-to-date. Finding stable **and** up-to-date C/C++ library was harder. While lib-mraa is very nice, especially when there is a need for cross-device development, they still have problems with pwm on BBB with 4.X kernels. It seems easier to me to use the same core lib for both python and c++. At least if something is broken after kernel/os update, it doesn't work the same way without extra surprises.

**Comment by pdp7** [comment]
@cocasema thanks, I've run pytest now on your cpplib branch and pytest ran OK.
```
debian@beaglebone:~/pr/adafruit-beaglebone-io-python$ git status
On branch cpplib
Your branch is up-to-date with 'origin/cpplib'.
nothing to commit, working directory clean

debian@beaglebone:~/pr/adafruit-beaglebone-io-python$ git log --oneline -4
60959b0 Add libadafruit-bbio with C++ wrappers for PWM/GPIO
655a112 Add syslog and debugging messages
92d61fb Extract BBIO_err into a separate header
a21b58e Declare PHONY targets in root Makefile
```

```
debian@beaglebone:~/pr/adafruit-beaglebone-io-python$ sudo pytest
========================================== test session starts ===========================================
platform linux2 -- Python 2.7.9, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /home/debian/pr/adafruit-beaglebone-io-python, inifile: 
collected 58 items 

test/test_adc.py ......
test/test_gpio_input.py ..
test/test_gpio_output.py ......
test/test_gpio_setup.py ..........
test/test_led.py ..
test/test_pwm_setup.py ...........................
test/test_spi.py ..
test/test_uart.py ...

======================================= 58 passed in 5.19 seconds ========================================
```

**Comment by pdp7** [comment]
@cocasema What is the best way for me to run tests for the C++ library functionality?

**Comment by pdp7** [comment]
NOTE: I had to install Debian package `dh-autoreconf` in order to run `make cpp`
```
debian@beaglebone:~/pr/adafruit-beaglebone-io-python$ make cpp
rm -f configure && \
autoreconf --install -I m4
/bin/sh: 2: autoreconf: not found
Makefile:38: recipe for target 'configure' failed
make: *** [configure] Error 127
```

```
debian@beaglebone:~/pr/adafruit-beaglebone-io-python$ sudo apt-get install dh-autoreconf
```

**Comment by pdp7** [comment]
@cocasema I am getting this error during `make cpp`:
```
g++ -DHAVE_CONFIG_H -I. -I../../source -I..  -DNDEBUG -g -O2 -fstack-protector-strong -fPIC -Wall -Wextra -Werror -DNO_PYTHON -I../../source/include/  -std=c++14 -g -O2 -MT examples/cpp/pwm.o -MD -MP -MF $depbase.Tpo -c -o examples/cpp/pwm.o ../../source/examples/cpp/pwm.cpp &&\
mv -f $depbase.Tpo $depbase.Po
../../source/examples/cpp/pwm.cpp: In function 'int main(int, char**)':
../../source/examples/cpp/pwm.cpp:34:58: error: could not convert '{7, nullptr, 32}' from '<brace-enclosed initializer list>' to 'adafruit::bbio::lib_options'
     adafruit::bbio::init({LOG_DEBUG, nullptr, LOG_PERROR});
                                                          ^
Makefile:550: recipe for target 'examples/cpp/pwm.o' failed
make[3]: *** [examples/cpp/pwm.o] Error 1
make[3]: Leaving directory '/home/debian/pr/adafruit-beaglebone-io-python/build/source'
Makefile:388: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/debian/pr/adafruit-beaglebone-io-python/build'
Makefile:319: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/debian/pr/adafruit-beaglebone-io-python/build'
Makefile:47: recipe for target 'cpp' failed
make: *** [cpp] Error 2
```

## Full log:
[adafruit_bbio_make_cpp_error.txt](https://gist.github.com/pdp7/aa8337ef4984c7f1808d6a8354917f26)

## System info:
```
debian@beaglebone:~/pr/adafruit-beaglebone-io-python$ uname -a
Linux beaglebone 4.4.48-ti-r88 #1 SMP Sun Feb 12 01:06:00 UTC 2017 armv7l GNU/Linux
debian@beaglebone:~/pr/adafruit-beaglebone-io-python$ cat /etc/debian_version 
8.7
debian@beaglebone:~/pr/adafruit-beaglebone-io-python$ cat /etc/dogtag 
BeagleBoard.org Debian Image 2017-02-12
```

**Comment by cocasema** [comment]
I see, looks like Debian has a bit older gcc.  I use Ubuntu 16.04 image.
I'll try Debian image and most likely need to downgrade to c++11.

**Comment by RobertCNelson** [comment]
@cocasema we need to be a little careful, in Debian Jessie (current stable) we have gcc (4.9.2 (Debian 4.9.2-10)) with the up-coming Debian Stretch we have gcc (6.3.0 20170205 (Debian 6.3.0-6))

In jessie, c++11 was experimental, and led to some issues when debian transitioned to gcc-5 (and then gcc-6)

https://wiki.debian.org/GCC5#libstdc.2B-.2B-_ABI_transition

Regards,

**Comment by cocasema** [comment]
That ABI change have already hurt me once during Ubuntu 14 -> 16 upgrade.
Xenial ended up shipping two versions of libraries - liffoobar & libfoobar_v5.

In the current c++ wrappers there is no real need in c++11 support. With a few minor changes I can make it c++98/03 compatible.
I didn't add .deb package assuming that the developers will need to compile libraries themselves with their version of gcc, so we should be ok.

**Comment by cocasema** [comment]
I updated c++ library to use minimal subset of c++11.

```
> uname -a
Linux beaglebone 4.4.9-ti-r25 #1 SMP Thu May 5 23:08:13 UTC 2016 armv7l GNU/Linux
> cat /etc/debian_version 
8.7
> cat /etc/dogtag 
BeagleBoard.org Debian Image 2016-05-13
> gcc --version
gcc (Debian 4.9.2-10) 4.9.2
```

**Comment by cocasema** [comment]
I think we can also "-D_GLIBCXX_USE_CXX11_ABI=0" to CXXFLAGS 
https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

**Comment by pdp7** [comment]
@cocasema I've just returned from a conference and will check this out

**Comment by cocasema** [comment]
```
/usr/local/include$ tree
.
└── adafruit
    ├── bbio
    │   ├── error.h
    │   ├── gpio.h
    │   └── pwm.h
    └── bbio.h

2 directories, 4 files

/usr/local/lib$ ls -la libadafruit-bbio*
-rwxr-xr-x 1 root root    984 Mar 19 06:02 libadafruit-bbio0.la
lrwxrwxrwx 1 root root     26 Mar 19 06:02 libadafruit-bbio0.so -> libadafruit-bbio0.so.0.0.0
lrwxrwxrwx 1 root root     26 Mar 19 06:02 libadafruit-bbio0.so.0 -> libadafruit-bbio0.so.0.0.0
-rwxr-xr-x 1 root root 222856 Mar 19 06:02 libadafruit-bbio0.so.0.0.0
-rwxr-xr-x 1 root root    984 Mar 19 06:02 libadafruit-bbio1.la
lrwxrwxrwx 1 root root     26 Mar 19 06:02 libadafruit-bbio1.so -> libadafruit-bbio1.so.0.0.0
lrwxrwxrwx 1 root root     26 Mar 19 06:02 libadafruit-bbio1.so.0 -> libadafruit-bbio1.so.0.0.0
-rwxr-xr-x 1 root root 247652 Mar 19 06:02 libadafruit-bbio1.so.0.0.0
```

**Comment by pdp7** [comment]
@cocasema I've merged two fixes today and looks like there is now a conflict in source/event_gpio.c.  Could you please have a look?  Thanks.

**Comment by cocasema** [comment]
```
test/test_adc.py ......
test/test_gpio_input.py ..
test/test_gpio_output.py ......
test/test_gpio_setup.py ..........
test/test_pwm_setup.py ...........................
test/test_spi.py ..
test/test_uart.py ...
```
```
./build/source/examples/cpp/pwm 
pwm: libadafruit-bbio version <unknown> initialized
pwm: initialize_pwm: OK
pwm: pwm_start: P8_19, 0.000000, 1000.000000, 0
pwm: lookup_exported_pwm: couldn't find 'P8_19'
pwm: pwm_setup: P8_19 OK
pwm: pwm_set_polarity: P8_19 0 OK
pwm: pwm_set_frequency: P8_19 1000.000000 OK
pwm: pwm_set_duty_cycle: P8_19 0.000000 OK
pwm: pwm_start: P8_19 OK
pwm: pwm_set_duty_cycle: P8_19 0.000000 OK
pwm: pwm_set_duty_cycle: P8_19 0.100000 OK
```
```
./build/source/examples/cpp/gpio 
gpio: libadafruit-bbio version <unknown> initialized
gpio: initialize_pwm: OK
gpio: gpio_export: 68 already exported
gpio: gpio_set_direction: 68 OK
gpio: gpio_set_value: 68 0 OK
gpio: gpio_set_value: 68 1 OK
gpio: gpio_set_value: 68 0 OK
```

**Comment by pdp7** [comment]
thanks

pytest runs OK;
```
debian@beaglebone:~/pr/pr135/adafruit-beaglebone-io-python$ sudo pytest
===================================================== test session starts =====================================================
platform linux2 -- Python 2.7.9, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /home/debian/pr/pr135/adafruit-beaglebone-io-python, inifile: 
collected 58 items 

test/test_adc.py ......
test/test_gpio_input.py ..
test/test_gpio_output.py ......
test/test_gpio_setup.py ..........
test/test_led.py ..
test/test_pwm_setup.py ...........................
test/test_spi.py ..
test/test_uart.py ...

================================================== 58 passed in 5.72 seconds ==================================================
debian@beaglebone:~/pr/pr135/adafruit-beaglebone-io-python$ uname -a 
Linux beaglebone 4.4.48-ti-r88 #1 SMP Sun Feb 12 01:06:00 UTC 2017 armv7l GNU/Linux
debian@beaglebone:~/pr/pr135/adafruit-beaglebone-io-python$ cat /etc/dogtag 
BeagleBoard.org Debian Image 2017-02-12
debian@beaglebone:~/pr/pr135/adafruit-beaglebone-io-python$ cat /etc/debian_version 
8.7
debian@beaglebone:~/pr/pr135/adafruit-beaglebone-io-python$ 
```

**Comment by pdp7** [comment]
@cocasema I'm trying to the run the tests examples for the cpp library and running into an error:

I ran `sudo make cpp-install` and then tried to run the pwm example:
```
debian@beaglebone:~/pr/pr135/adafruit-beaglebone-io-python$ sudo ./build/source/examples/cpp/pwm 
pwm: libadafruit-bbio version <unknown> initialized
pwm: pwm_start: P8_19, 0.000000, 1000.000000, 0
pwm: lookup_exported_pwm: couldn't find 'P8_19'
pwm: pwm_start: P8_19 pwm setup failed: 2
terminate called after throwing an instance of 'adafruit::bbio::BBIOError'
  what():  2-SYSFS 
```
I looks like it is not using the correct path for slots:
```
debian@beaglebone:~/pr/pr135/adafruit-beaglebone-io-python$ strace -e open,read ./build/source/examples/cpp/pwm  2>&1 |grep slots
open("/slots", O_RDWR)                  = -1 ENOENT (No such file or directory)
open("/slots", O_RDWR)                  = -1 ENOENT (No such file or directory)
debian@beaglebone:~/pr/pr135/adafruit-beaglebone-io-python$ 
```

**Comment by pdp7** [comment]
@cocasema any suggestions about this error?
```
terminate called after throwing an instance of 'adafruit::bbio::BBIOError'
  what():  2-SYSFS 
```

**Comment by cocasema** [comment]
@pdp7 I'd suspect it's around BBBVERSION41 macro. I've tested this on Ubuntu16 image.
I hope to flash BBB with Debian over weekend and add tests.

**Comment by cocasema** [comment]
```
cat /etc/dogtag 
BeagleBoard.org Debian Image 2017-03-19

sudo  build/source/test/cpp/unittest 
...
[==========] 21 tests from 1 test case ran. (398 ms total)
[  PASSED  ] 21 tests.
```
```
cat /etc/dogtag 
rcn-ee.net console Ubuntu Image 2016-06-09

sudo build/source/test/cpp/unittest 
...
[==========] 21 tests from 1 test case ran. (381 ms total)
[  PASSED  ] 21 tests.
```

**Comment by pdp7** [comment]
@cocasema thanks, should I try again?  Which make command should I run before I run the cpp library tests?

**Comment by cocasema** [comment]
To build the library:
```
sudo apt-get install automake libgtest-dev
make clean
make cpp
```
To run tests (this will also build if needed):
`make cpp-check `

If you are not root, pwm test most likely will fail for you due to permissions. so you can either do `sudo make cpp-check` or just run it manually `sudo build/source/test/cpp/unittest`

I also have these commands in .profile:
```
sudo sh -c 'echo cape-universaln > /sys/devices/platform/bone_capemgr/slots'
sudo sh -c 'echo pwm > /sys/devices/platform/ocp/ocp\:P9_16_pinmux/state'
sudo sh -c 'echo pwm > /sys/devices/platform/ocp/ocp\:P8_19_pinmux/state'
```

**Comment by pdp7** [comment]
@cocasema thanks, the cpp tests run OK now for me with the above instructions

**Comment by pdp7** [comment]
Successful test results after merge:
```
debian@beaglebone:~/adafruit-beaglebone-io-python$ cat /etc/debian_version 
8.7
debian@beaglebone:~/adafruit-beaglebone-io-python$ cat /etc/dogtag 
BeagleBoard.org Debian Image 2017-02-12
debian@beaglebone:~/adafruit-beaglebone-io-python$ uname -a
Linux beaglebone 4.4.48-ti-r88 #1 SMP Sun Feb 12 01:06:00 UTC 2017 armv7l GNU/Linux
debian@beaglebone:~/adafruit-beaglebone-io-python$ sudo pytest
===================================================== test session starts =====================================================
platform linux2 -- Python 2.7.9, pytest-3.0.6, py-1.4.32, pluggy-0.4.0
rootdir: /home/debian/adafruit-beaglebone-io-python, inifile: 
collected 58 items 

test/test_adc.py ......
test/test_gpio_input.py ..
test/test_gpio_output.py ......
test/test_gpio_setup.py ..........
test/test_led.py ..
test/test_pwm_setup.py ...........................
test/test_spi.py ..
test/test_uart.py ...

================================================== 58 passed in 5.22 seconds ==================================================
debian@beaglebone:~/adafruit-beaglebone-io-python$ sudo make cpp-check
cd build && \
make build
make[1]: Entering directory '/home/debian/adafruit-beaglebone-io-python/build'
make[1]: Nothing to be done for '../build'.
make[1]: Leaving directory '/home/debian/adafruit-beaglebone-io-python/build'
cd build && \
make check
make[1]: Entering directory '/home/debian/adafruit-beaglebone-io-python/build'
Making check in source
make[2]: Entering directory '/home/debian/adafruit-beaglebone-io-python/build/source'
make  check-am
make[3]: Entering directory '/home/debian/adafruit-beaglebone-io-python/build/source'
make  test/cpp/abi-old test/cpp/abi-new test/cpp/unittest
make[4]: Entering directory '/home/debian/adafruit-beaglebone-io-python/build/source'
make[4]: 'test/cpp/abi-old' is up to date.
make[4]: 'test/cpp/abi-new' is up to date.
make[4]: 'test/cpp/unittest' is up to date.
make[4]: Leaving directory '/home/debian/adafruit-beaglebone-io-python/build/source'
make  check-TESTS
make[4]: Entering directory '/home/debian/adafruit-beaglebone-io-python/build/source'
make[5]: Entering directory '/home/debian/adafruit-beaglebone-io-python/build/source'
PASS: test/cpp/abi-old
PASS: test/cpp/abi-new
PASS: test/cpp/unittest
make[6]: Entering directory '/home/debian/adafruit-beaglebone-io-python/build/source'
make  all-am
make[7]: Entering directory '/home/debian/adafruit-beaglebone-io-python/build/source'
make[7]: Nothing to be done for 'all-am'.
make[7]: Leaving directory '/home/debian/adafruit-beaglebone-io-python/build/source'
make[6]: Leaving directory '/home/debian/adafruit-beaglebone-io-python/build/source'
============================================================================
Testsuite summary for Adafruit BeagleBone IO Library 1.0.0
============================================================================
# TOTAL: 3
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[5]: Leaving directory '/home/debian/adafruit-beaglebone-io-python/build/source'
make[4]: Leaving directory '/home/debian/adafruit-beaglebone-io-python/build/source'
make[3]: Leaving directory '/home/debian/adafruit-beaglebone-io-python/build/source'
make[2]: Leaving directory '/home/debian/adafruit-beaglebone-io-python/build/source'
make[2]: Entering directory '/home/debian/adafruit-beaglebone-io-python/build'
make[2]: Leaving directory '/home/debian/adafruit-beaglebone-io-python/build'
make[1]: Leaving directory '/home/debian/adafruit-beaglebone-io-python/build'
debian@beaglebone:~/adafruit-beaglebone-io-python$ 
```

**Pull request merged**
